[workspace.package]
edition = "2024"
license = "GNU GPLv3"
repository = "https://github.com/liamsnow/igloo"
rust-version = "1.93.0"

[workspace.dependencies]

[workspace]
members = ["./crates/*"]
resolver = "2"
